
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Strawberry/c/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt"
    message: |
      The system is: Windows - 6.2.9200 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Strawberry/c/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Strawberry/c/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Strawberry/c/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild-Version 17.9.5+33de0b227 für .NET Framework
      Der Buildvorgang wurde am 18.04.2024 13:21:52 gestartet.
      
      Projekt "C:\\Users\\david\\Desktop\\DEMO_SDK\\eego-sdk-pybind11-master\\python3\\CMakeFiles\\3.26.4\\CompilerIdC\\CompilerIdC.vcxproj" auf Knoten "1" (Standardziele).
      PrepareForBuild:
        Das Verzeichnis "Debug\\" wird erstellt.
        Die strukturierte Ausgabe ist aktiviert. Die Formatierung der Compilerdiagnose spiegelt die Fehlerhierarchie wider. Weitere Informationen finden Sie unter https://aka.ms/cpp/structured-output.
        Das Verzeichnis "Debug\\CompilerIdC.tlog\\" wird erstellt.
      InitializeBuildStatus:
        "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" wird erstellt, da "AlwaysCreate" angegeben wurde.
        Aktualisieren des Timestamps von "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\Users\\david\\Desktop\\DEMO_SDK\\eego-sdk-pybind11-master\\python3\\CMakeFiles\\3.26.4\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Die Datei "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" wird gelöscht.
        Aktualisieren des Timestamps von "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Die Erstellung von Projekt "C:\\Users\\david\\Desktop\\DEMO_SDK\\eego-sdk-pybind11-master\\python3\\CMakeFiles\\3.26.4\\CompilerIdC\\CompilerIdC.vcxproj" ist abgeschlossen (Standardziele).
      
      Der Buildvorgang wurde erfolgreich ausgeführt.
          0 Warnung(en)
          0 Fehler
      
      Verstrichene Zeit 00:00:01.76
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/david/Desktop/DEMO_SDK/eego-sdk-pybind11-master/python3/CMakeFiles/3.26.4/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Strawberry/c/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Strawberry/c/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Strawberry/c/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild-Version 17.9.5+33de0b227 für .NET Framework
      Der Buildvorgang wurde am 18.04.2024 13:21:54 gestartet.
      
      Projekt "C:\\Users\\david\\Desktop\\DEMO_SDK\\eego-sdk-pybind11-master\\python3\\CMakeFiles\\3.26.4\\CompilerIdCXX\\CompilerIdCXX.vcxproj" auf Knoten "1" (Standardziele).
      PrepareForBuild:
        Das Verzeichnis "Debug\\" wird erstellt.
        Die strukturierte Ausgabe ist aktiviert. Die Formatierung der Compilerdiagnose spiegelt die Fehlerhierarchie wider. Weitere Informationen finden Sie unter https://aka.ms/cpp/structured-output.
        Das Verzeichnis "Debug\\CompilerIdCXX.tlog\\" wird erstellt.
      InitializeBuildStatus:
        "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" wird erstellt, da "AlwaysCreate" angegeben wurde.
        Aktualisieren des Timestamps von "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\Users\\david\\Desktop\\DEMO_SDK\\eego-sdk-pybind11-master\\python3\\CMakeFiles\\3.26.4\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Die Datei "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" wird gelöscht.
        Aktualisieren des Timestamps von "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Die Erstellung von Projekt "C:\\Users\\david\\Desktop\\DEMO_SDK\\eego-sdk-pybind11-master\\python3\\CMakeFiles\\3.26.4\\CompilerIdCXX\\CompilerIdCXX.vcxproj" ist abgeschlossen (Standardziele).
      
      Der Buildvorgang wurde erfolgreich ausgeführt.
          0 Warnung(en)
          0 Fehler
      
      Verstrichene Zeit 00:00:01.50
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/david/Desktop/DEMO_SDK/eego-sdk-pybind11-master/python3/CMakeFiles/3.26.4/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Strawberry/c/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Strawberry/c/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/david/Desktop/DEMO_SDK/eego-sdk-pybind11-master/python3/CMakeFiles/CMakeScratch/TryCompile-hga1a5"
      binary: "C:/Users/david/Desktop/DEMO_SDK/eego-sdk-pybind11-master/python3/CMakeFiles/CMakeScratch/TryCompile-hga1a5"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: C:/Users/david/Desktop/DEMO_SDK/eego-sdk-pybind11-master/python3/CMakeFiles/CMakeScratch/TryCompile-hga1a5
        
        Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_f573f.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n && MSBuild-Version 17.9.5+33de0b227 für .NET Framework
        Der Buildvorgang wurde am 18.04.2024 13:21:56 gestartet.
        
        Projekt "C:\\Users\\david\\Desktop\\DEMO_SDK\\eego-sdk-pybind11-master\\python3\\CMakeFiles\\CMakeScratch\\TryCompile-hga1a5\\cmTC_f573f.vcxproj" auf Knoten "1" (Standardziele).
        PrepareForBuild:
          Das Verzeichnis "cmTC_f573f.dir\\Debug\\" wird erstellt.
          Die strukturierte Ausgabe ist aktiviert. Die Formatierung der Compilerdiagnose spiegelt die Fehlerhierarchie wider. Weitere Informationen finden Sie unter https://aka.ms/cpp/structured-output.
          Das Verzeichnis "C:\\Users\\david\\Desktop\\DEMO_SDK\\eego-sdk-pybind11-master\\python3\\CMakeFiles\\CMakeScratch\\TryCompile-hga1a5\\Debug\\" wird erstellt.
          Das Verzeichnis "cmTC_f573f.dir\\Debug\\cmTC_f573f.tlog\\" wird erstellt.
        InitializeBuildStatus:
          "cmTC_f573f.dir\\Debug\\cmTC_f573f.tlog\\unsuccessfulbuild" wird erstellt, da "AlwaysCreate" angegeben wurde.
          Aktualisieren des Timestamps von "cmTC_f573f.dir\\Debug\\cmTC_f573f.tlog\\unsuccessfulbuild".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_f573f.dir\\Debug\\\\" /Fd"cmTC_f573f.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Strawberry\\c\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c"
          Microsoft (R) C/C++-Optimierungscompiler Version 19.39.33520 für x64
          Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_f573f.dir\\Debug\\\\" /Fd"cmTC_f573f.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Strawberry\\c\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c"
          CMakeCCompilerABI.c
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\david\\Desktop\\DEMO_SDK\\eego-sdk-pybind11-master\\python3\\CMakeFiles\\CMakeScratch\\TryCompile-hga1a5\\Debug\\cmTC_f573f.exe" /INCREMENTAL /ILK:"cmTC_f573f.dir\\Debug\\cmTC_f573f.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/david/Desktop/DEMO_SDK/eego-sdk-pybind11-master/python3/CMakeFiles/CMakeScratch/TryCompile-hga1a5/Debug/cmTC_f573f.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/david/Desktop/DEMO_SDK/eego-sdk-pybind11-master/python3/CMakeFiles/CMakeScratch/TryCompile-hga1a5/Debug/cmTC_f573f.lib" /MACHINE:X64  /machine:x64 cmTC_f573f.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_f573f.vcxproj -> C:\\Users\\david\\Desktop\\DEMO_SDK\\eego-sdk-pybind11-master\\python3\\CMakeFiles\\CMakeScratch\\TryCompile-hga1a5\\Debug\\cmTC_f573f.exe
        FinalizeBuildStatus:
          Die Datei "cmTC_f573f.dir\\Debug\\cmTC_f573f.tlog\\unsuccessfulbuild" wird gelöscht.
          Aktualisieren des Timestamps von "cmTC_f573f.dir\\Debug\\cmTC_f573f.tlog\\cmTC_f573f.lastbuildstate".
        Die Erstellung von Projekt "C:\\Users\\david\\Desktop\\DEMO_SDK\\eego-sdk-pybind11-master\\python3\\CMakeFiles\\CMakeScratch\\TryCompile-hga1a5\\cmTC_f573f.vcxproj" ist abgeschlossen (Standardziele).
        
        Der Buildvorgang wurde erfolgreich ausgeführt.
            0 Warnung(en)
            0 Fehler
        
        Verstrichene Zeit 00:00:01.44
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Strawberry/c/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Strawberry/c/share/cmake-3.26/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/david/Desktop/DEMO_SDK/eego-sdk-pybind11-master/python3/CMakeFiles/CMakeScratch/TryCompile-f0zcka"
      binary: "C:/Users/david/Desktop/DEMO_SDK/eego-sdk-pybind11-master/python3/CMakeFiles/CMakeScratch/TryCompile-f0zcka"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: C:/Users/david/Desktop/DEMO_SDK/eego-sdk-pybind11-master/python3/CMakeFiles/CMakeScratch/TryCompile-f0zcka
        
        Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_392cb.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n && MSBuild-Version 17.9.5+33de0b227 für .NET Framework
        Der Buildvorgang wurde am 18.04.2024 13:21:59 gestartet.
        
        Projekt "C:\\Users\\david\\Desktop\\DEMO_SDK\\eego-sdk-pybind11-master\\python3\\CMakeFiles\\CMakeScratch\\TryCompile-f0zcka\\cmTC_392cb.vcxproj" auf Knoten "1" (Standardziele).
        PrepareForBuild:
          Das Verzeichnis "cmTC_392cb.dir\\Debug\\" wird erstellt.
          Die strukturierte Ausgabe ist aktiviert. Die Formatierung der Compilerdiagnose spiegelt die Fehlerhierarchie wider. Weitere Informationen finden Sie unter https://aka.ms/cpp/structured-output.
          Das Verzeichnis "C:\\Users\\david\\Desktop\\DEMO_SDK\\eego-sdk-pybind11-master\\python3\\CMakeFiles\\CMakeScratch\\TryCompile-f0zcka\\Debug\\" wird erstellt.
          Das Verzeichnis "cmTC_392cb.dir\\Debug\\cmTC_392cb.tlog\\" wird erstellt.
        InitializeBuildStatus:
          "cmTC_392cb.dir\\Debug\\cmTC_392cb.tlog\\unsuccessfulbuild" wird erstellt, da "AlwaysCreate" angegeben wurde.
          Aktualisieren des Timestamps von "cmTC_392cb.dir\\Debug\\cmTC_392cb.tlog\\unsuccessfulbuild".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_392cb.dir\\Debug\\\\" /Fd"cmTC_392cb.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Strawberry\\c\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
          Microsoft (R) C/C++-Optimierungscompiler Version 19.39.33520 für x64
          Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_392cb.dir\\Debug\\\\" /Fd"cmTC_392cb.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Strawberry\\c\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
          CMakeCXXCompilerABI.cpp
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\david\\Desktop\\DEMO_SDK\\eego-sdk-pybind11-master\\python3\\CMakeFiles\\CMakeScratch\\TryCompile-f0zcka\\Debug\\cmTC_392cb.exe" /INCREMENTAL /ILK:"cmTC_392cb.dir\\Debug\\cmTC_392cb.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/david/Desktop/DEMO_SDK/eego-sdk-pybind11-master/python3/CMakeFiles/CMakeScratch/TryCompile-f0zcka/Debug/cmTC_392cb.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/david/Desktop/DEMO_SDK/eego-sdk-pybind11-master/python3/CMakeFiles/CMakeScratch/TryCompile-f0zcka/Debug/cmTC_392cb.lib" /MACHINE:X64  /machine:x64 cmTC_392cb.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_392cb.vcxproj -> C:\\Users\\david\\Desktop\\DEMO_SDK\\eego-sdk-pybind11-master\\python3\\CMakeFiles\\CMakeScratch\\TryCompile-f0zcka\\Debug\\cmTC_392cb.exe
        FinalizeBuildStatus:
          Die Datei "cmTC_392cb.dir\\Debug\\cmTC_392cb.tlog\\unsuccessfulbuild" wird gelöscht.
          Aktualisieren des Timestamps von "cmTC_392cb.dir\\Debug\\cmTC_392cb.tlog\\cmTC_392cb.lastbuildstate".
        Die Erstellung von Projekt "C:\\Users\\david\\Desktop\\DEMO_SDK\\eego-sdk-pybind11-master\\python3\\CMakeFiles\\CMakeScratch\\TryCompile-f0zcka\\cmTC_392cb.vcxproj" ist abgeschlossen (Standardziele).
        
        Der Buildvorgang wurde erfolgreich ausgeführt.
            0 Warnung(en)
            0 Fehler
        
        Verstrichene Zeit 00:00:01.28
        
      exitCode: 0
...
